# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-07 22:12
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('smile', models.CharField(max_length=100, null=True, unique=True)),
                ('fingerprint', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=2048)),
                ('gap', models.FloatField(null=True)),
            ],
        ),
    ]
