# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-07 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='molecule',
            name='gap',
            field=models.FloatField(null=True),
        ),
    ]
