# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-08 01:37
from __future__ import unicode_literals

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humo', '0002_molecule_gap'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='molecule',
            index=django.contrib.postgres.indexes.GinIndex(fields=['fingerprint'], name='humo_molecu_fingerp_f4500f_gin'),
        ),
    ]
