# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-08 02:16
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humo', '0003_auto_20180208_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='molecule',
            name='coulomb_eigenspace',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
    ]
